YZLSM support for LCM
ephoris/endure-torch pull request #31
Opened 2024-09-14 22:37 UTC by aquaorifice

2024-09-15 17:55 UTC, ephoris commented
Can you double-check why the pytest is failing @aquaorifice? At some point we should make more of these sanity check tests.

2024-09-17 14:40 UTC, ephoris requested changes

2024-09-17 14:40 UTC, ephoris commented on endure/lcm/util/util.py
> +    categories = max_t - min_t + 1
I do not think we need the minus 1 here, since we do not want to include the last element. Were you running into errors keeping this here?

2024-09-17 14:40 UTC, ephoris commented on endure/lcm/model/yzlsm_model.py
> +OUT_WIDTH = 4
We can delete this. It's from an older version of the code.

2024-09-17 14:40 UTC, ephoris commented on endure/ltune/model/yzlsm_tuner.py
> +        y = nn.functional.gumbel_softmax(y, tau=temp, hard=hard)
We will need to add compatability for `reinmax` if we decide to also train with it.

2024-09-30 15:16 UTC, ephoris reviewed
I think this is good to go now? Can you double check @aquaorifice

2024-09-30 15:16 UTC, ephoris approved these changes

2024-09-30 15:19 UTC, aquaorifice commented
Does not seem like there is any conflict. I think this should be fine to merge.

2024-09-30 15:20 UTC, merged